### ISSUE TITLE
Lingua PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.play0ad.zeroad#1]
Lingua PT-BR não funciona

**Comment by Alexander-Wilms** [comment]
That's strange. the .po file for pt_BR is moved to /app/share/games/0ad/l10n and for me the UI is localized into German.

**Comment by Alexander-Wilms** [comment]
Can you update and check if alpha 22 fixes this?

**Comment by LeandroStanger** [comment]
Não consigo baixar nada

**Comment by LeandroStanger** [comment]
@Alexander-Wilms 
was successfully fixed
Sorry for the delay to respond

**Comment by Alexander-Wilms** [comment]
No problem. Thanks for the feedback.
