### ISSUE TITLE
update to Alpha 24

### ISSUE THREAD

**Issue by eszlari** [flathub/com.play0ad.zeroad#12]
https://play0ad.com/new-release-0-a-d-alpha-24-xsayarsa/

**Comment by MaCroX95** [comment]
+1, Yes please!

**Comment by Pockets-byte** [comment]
seconded

**Comment by Alexander-Wilms** [comment]
I encountered the same error after updating the manifest: https://github.com/flathub/com.play0ad.zeroad/pull/14

**Comment by gasinvein** [comment]
Fixed by #15

**Comment by Pockets-byte** [comment]
thanks. so shouldn't this issue be closed now?
