### ISSUE TITLE
/usr/bin/env: ‘bash’: No such file or directory

### ISSUE THREAD

**Issue by illwieckz** [flathub/com.play0ad.zeroad#18]
I tried to install and run this Flatpak for 0.0.24 version of 0 A.D. on Ubuntu 20.04, and I got this:

```bash
$ flatpak run com.play0ad.zeroad
/usr/bin/env: ‘bash’: No such file or directory
error: ldconfig failed, exit status 32512
```

**Comment by corecontingency** [comment]
Is this still happening? I created a new Ubuntu 20.04 virtual machine to try and reproduce, and I couldn't. The flatpak'd 0ad works fine.

Seems like your 0ad flatpak installation might be borked. Maybe try `flatpak update`, followed by `flatpak uninstall --delete-data com.play0ad.zeroad` (watch out, this might also delete your save files, as it clears the ~/.var/app directory), and then `flatpak install flathub com.play0ad.zeroad` to do a complete reinstallation?

**Comment by illwieckz** [comment]
Yes I reinstalled the flatpak and I still get the issue (note: that's the first time I try to install 0ad as a flatpak, so I didn't care about wiping everything).

**Comment by illwieckz** [comment]
For information I also did:

```sh
sudo flatpak repair --system --reinstall-all
```

And that fixed nothing.

**Comment by illwieckz** [comment]
This is not 0 A.D. flatpak fault, see https://github.com/flatpak/flatpak/issues/4315
