### ISSUE TITLE
publish aarch64 builds for 0.0.24

### ISSUE THREAD

**Issue by eighthave** [flathub/com.play0ad.zeroad#25]
0 A.D. works great a bunch of different ARM an aarch64 hardware, including recent Raspberry Pis, Chromebooks, MacBook M1, etc.  Please publish  arm and aarch64 builds.  0.0.23 is included for `arm`, most ARM laptops and desktops are 64-bit now.

**Comment by hfiguiere** [comment]
FWIW arm (32-bits) is no longer supported with the 20.08 sdk.

**Comment by eighthave** [comment]
Ok, leaving out `arm` seems fine, the large majority of the relevant hardware is 64-bit `aarch64` anyway.  I'm running the `aarch64` build locally, and will report back on what happens.

**Comment by eighthave** [comment]
I have built `com.play0ad.zeroad` on Debian/aarch64 on a Raspberry Pi and played it there.  It works, so I'm wondering why it was specifically excluded in the packaging here.

**Comment by eighthave** [comment]
@Alexander-Wilms looking at the git history, it looks like you disabled `aarch64` in 2017.  Things have changed, it works well now.
