### ISSUE TITLE
0 A.D. is not appearing in the Endless OS program center

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.play0ad.zeroad#3]
![captura de tela de 2018-06-03 22-04-15](https://user-images.githubusercontent.com/26097419/40893728-14b9c88e-677a-11e8-9560-a359586d9a24.png)

**Comment by Alexander-Wilms** [comment]
Does adding the second period help? Does it it appear when browsing the games category? Since it shows up on flathub.org, I don't think there's anything wrong with the metadata.

**Comment by LeandroStanger** [comment]
@nedrichards could help?

**Comment by nedrichards** [comment]
I believe that there is actually something wrong with the appstream. I'll build it myself and have a look.

**Comment by Alexander-Wilms** [comment]
This issue: https://github.com/flatpak/flatpak-builder/issues/155 ?

**Comment by nedrichards** [comment]
That's it

**Comment by Alexander-Wilms** [comment]
Should be fixed by https://github.com/flathub/com.play0ad.zeroad/commit/d6136d4746d79947768ed199213af0ffbce8862d

**Comment by nedrichards** [comment]
The build fails with `metainfo` not found I think the file is actually in `appdata`
