### ISSUE TITLE
Update to Alpha 23.1

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/com.play0ad.zeroad#6]
It seems this build has not been updated from several months ago when 23.1 was released (not just 23, this is a re-release). I can connect to the general lobby but it says me that I must update to 23.1 (already in Debian stable repositories).

https://play0ad.com/re-release-of-0-a-d-alpha-23-ken-wood/

**Comment by EchedeyLR** [comment]
cc @Alexander-Wilms @barthalion

**Comment by EchedeyLR** [comment]
@AsciiWolf could you look into this?

**Comment by corecontingency** [comment]
Resolved by pull request #8.
